import { parse } from "mathjs";

export type MathIssue={code:string;message:string;excerpt:string;severity:"warning"|"error"};
export type ExtractedEquation={raw:string;normalized:string;latex:string;valid:boolean;issues:MathIssue[]};
export type MathMeta={suspicious:boolean;replacements:number;equations:ExtractedEquation[];issues:MathIssue[]};
const MAP:Record<string,string>={"\uF02D":"−","\uF0B4":"×","\uF0B8":"÷","\uF0A3":"≤","\uF0B3":"≥","\uF0B9":"≠","\uF0D6":"√","\uF0B1":"±","\u2212":"−","\u2010":"−","\u2011":"−","\u2012":"−","\u2013":"−","\u2014":"−","\u2044":"/"};
const CONTROL=/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g;
const PRIVATE=/[\uE000-\uF8FF]/g;
function ascii(s:string){return s.replace(/[−–—]/g,"-").replace(/×/g,"*").replace(/÷/g,"/").replace(/²/g,"^2").replace(/³/g,"^3").replace(/√\s*([\w.]+)/g,"sqrt($1)");}
function latex(s:string){return s.replace(/−/g,"-").replace(/×/g,"\\times ").replace(/÷/g,"\\div ").replace(/≤/g,"\\le ").replace(/≥/g,"\\ge ").replace(/≠/g,"\\ne ").replace(/√\s*([\w.]+)/g,"\\sqrt{$1}").replace(/²/g,"^{2}").replace(/³/g,"^{3}");}
function balanced(s:string){const st:string[]=[];const p:Record<string,string>={")":"(","]":"[","}":"{"};for(const c of s){if("([{".includes(c))st.push(c);else if(p[c]&&st.pop()!==p[c])return false;}return !st.length;}
function equation(raw:string,norm:string):ExtractedEquation{const issues:MathIssue[]=[];if(!balanced(norm))issues.push({code:"UNBALANCED_DELIMITER",message:"Unbalanced brackets",excerpt:norm,severity:"error"});if(/\b\d*[A-Za-z]\s+\d*[A-Za-z]\s*=/.test(norm))issues.push({code:"POSSIBLE_MISSING_OPERATOR",message:"Possible missing operator",excerpt:norm,severity:"warning"});try{for(const side of ascii(norm).split(/=(?!=)/)){if(side.trim())parse(side.trim());}}catch{issues.push({code:"UNPARSEABLE_EQUATION",message:"Equation could not be parsed",excerpt:norm,severity:"warning"});}return{raw,normalized:norm,latex:latex(norm),valid:!issues.some(i=>i.severity==="error"),issues};}
export function normalizeMathText(input:string):{text:string}&MathMeta{const raw=String(input||"");const issues:MathIssue[]=[];let replacements=0;let text="";for(const c of raw.normalize("NFKC")){if(MAP[c]){text+=MAP[c];replacements++;}else text+=c;}if(CONTROL.test(text)){issues.push({code:"CONTROL_CHARACTER",message:"Removed unsafe PDF control character",excerpt:text.match(CONTROL)?.[0]||"",severity:"warning"});CONTROL.lastIndex=0;text=text.replace(CONTROL,"");}if(text.includes("�"))issues.push({code:"REPLACEMENT_CHARACTER",message:"Unknown replacement character",excerpt:"�",severity:"error"});if(PRIVATE.test(text)){PRIVATE.lastIndex=0;issues.push({code:"PRIVATE_USE_GLYPH",message:"Unknown embedded-font glyph needs OCR",excerpt:text.match(PRIVATE)?.[0]||"",severity:"error"});PRIVATE.lastIndex=0;text=text.replace(PRIVATE," ⟦GLYPH?⟧ ");}text=text.replace(/\u00A0/g," ").replace(/[ \t]+/g," ").replace(/ *\n */g,"\n").replace(/\n{3,}/g,"\n\n").trim();const rawLines=raw.split(/\r?\n/),lines=text.split(/\r?\n/);const equations=lines.flatMap((line,i)=>{const n=line.trim();return n.length<=260&&/[=≤≥≠√+−×÷*\/^]/.test(n)&&/[A-Za-z0-9]/.test(n)?[equation(rawLines[i]||n,n)]:[];});const all=[...issues,...equations.flatMap(e=>e.issues)];return{text,equations,issues:all,replacements,suspicious:all.length>0};}
export function normalizePages(pages:Array<{page:number;text:string}>){let replacementCount=0,suspiciousPages=0,equationCount=0,issueCount=0;const out=pages.map(p=>{const r=normalizeMathText(p.text);replacementCount+=r.replacements;equationCount+=r.equations.length;issueCount+=r.issues.length;if(r.suspicious)suspiciousPages++;return{...p,text:r.text,math:{suspicious:r.suspicious,replacements:r.replacements,equations:r.equations,issues:r.issues}};});return{pages:out,diagnostics:{replacementCount,suspiciousPages,equationCount,issueCount}};}
