import { NextResponse } from "next/server";
import { rangeChunks, search } from "@/lib/rag/store";
import { callGemini, languageInstruction } from "@/lib/teacher-prompts";
import { parseAiJson } from "@/lib/safe-json";
import { normalizeLessonVisuals, LESSON_VISUAL_INSTRUCTION } from "@/lib/visual-generation";
import { teachingLanguageInstruction } from "@/lib/language-preferences";
import { normalizeWhiteboardPlan, WHITEBOARD_COMMAND_JSON_INSTRUCTION } from "@/lib/whiteboard-commands";
export const runtime="nodejs";
export async function POST(req:Request){ const {topic,documentId,grade="8",languageId="english",sourceLanguage="english",teachingLanguage=languageId,materialLanguage="english",teachingStyle="target_with_english_terms",pageStart,pageEnd, apiKey}=await req.json(); if(!topic) return NextResponse.json({error:"Topic is required"},{status:400}); const ranged=Number.isFinite(Number(pageStart))&&Number.isFinite(Number(pageEnd)); const hits=ranged?await rangeChunks(documentId,Number(pageStart),Number(pageEnd),30):await search(topic,8,documentId); if(!hits.length) return NextResponse.json({error:"No relevant textbook material found"},{status:404}); const context=hits.map((h,i)=>`[S${i+1}] page ${h.page}: ${h.text}`).join("\n\n"); const fallbackBase=normalizeLessonVisuals({title:topic,scenes:[{type:"teacher",title:"Introduction",narration:`Today we will learn ${topic} from the selected textbook.`,board:[hits[0].text.slice(0,220)],question:"What do you already know about this topic?"},{type:"explain",title:"Key idea",narration:hits[0].text.slice(0,500),board:hits.slice(0,3).map(h=>h.text.slice(0,150)),question:"Can you explain the key idea in your own words?"},{type:"quiz",title:"Check your understanding",narration:"Choose the best answer using the textbook lesson.",board:[],question:`What is the main idea of ${topic}?`}],sources:hits.map((h,i)=>({id:`S${i+1}`,page:h.page,text:h.text.slice(0,240) }))}); const fallback={...fallbackBase,scenes:fallbackBase.scenes.map((scene:any)=>({...scene,whiteboardCommands:normalizeWhiteboardPlan(scene.whiteboardCommands,scene.board||[])}))}; try{ const raw=await callGemini(`Create a short interactive classroom lesson for a Class ${grade} student. Use ONLY the supplied textbook extracts. ${teachingLanguageInstruction({sourceLanguage,teachingLanguage,materialLanguage,teachingStyle})} Return raw JSON exactly: {"title":"...","scenes":[{"type":"teacher|explain|discussion|quiz","title":"...","narration":"...","board":["..."],"question":"...","visual":{...validated Visual object...},"whiteboardCommands":{"version":1,"autoplay":true,"commands":[...]}}],"sources":[{"id":"S1","page":1,"text":"..."}]}. ${LESSON_VISUAL_INSTRUCTION} ${WHITEBOARD_COMMAND_JSON_INSTRUCTION} Make 4-6 scenes. Include source IDs in narration where relevant.`,`Topic: ${topic}\n\n${context}`,{maxOutputTokens:16384,json:true}, apiKey); const base=normalizeLessonVisuals(parseAiJson(raw)); const lesson={...base,scenes:base.scenes.map((scene:any)=>({...scene,whiteboardCommands:normalizeWhiteboardPlan(scene.whiteboardCommands,scene.board||[],scene.narration)}))}; return NextResponse.json({lesson}); }catch{return NextResponse.json({lesson:fallback});} }
